<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>disable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="PhysicsInterop.cs" />
    <Compile Include="Renderer.cs" />
    <Compile Include="ToolController.cs" />
    <Compile Include="BlackHole.cs" />
    <Compile Include="SandboxCanvas.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Update="sandbox_core.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
